language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - psql -U postgres -c 'CREATE DATABASE "oc";'
script:
  - python manage.py test --settings=settings.test
